FROM quay.io/rpsene/ibmcloud-ops:powervs-data-insert

LABEL authors="Rafael Sene - rpsene@br.ibm.com"

WORKDIR /input

COPY ./query.py .
COPY ./postgres.ini .
COPY ./ssl.crt .

ENV LANG=en_US.UTF-8

ENTRYPOINT ["/usr/bin/python3", "./query.py"]
